ifeq ($(PY),)
	#PY := ../../../micropython/ports/unix/micropython
	PY := micropython
endif

all-tests:
	$(PY) test_bitarray.py
	$(PY) test_bitarray2.py
	$(PY) test_bitmap.py
	$(PY) test_ruleman.py
	$(PY) test_simsched.py
