import micro_enum

DEFAULT_FRAGMENT_RID = 1
DEFAULT_L2_SIZE = 8
DEFAULT_RECV_BUFSIZE = 512
DEFAULT_TIMER_T1 = 5
DEFAULT_TIMER_T2 = 10
DEFAULT_TIMER_T3 = 10
DEFAULT_TIMER_T4 = 12
DEFAULT_TIMER_T5 = 14

SCHC_MODE = micro_enum.enum(
    NO_ACK = 1,
    ACK_ALWAYS = 2,
    ACK_ON_ERROR = 3
    )
