#from enum import Enum, unique, auto

DEFAULT_FRAGMENT_RID = 1
DEFAULT_L2_SIZE = 8
DEFAULT_RECV_BUFSIZE = 512
DEFAULT_TIMER_T1 = 5
DEFAULT_TIMER_T2 = 10
DEFAULT_TIMER_T3 = 10
DEFAULT_TIMER_T4 = 12
DEFAULT_TIMER_T5 = 14

#class SCHC_MODE(Enum)
class SCHC_MODE():
    NO_ACK = 0
    ACK_ALWAYS = 1
    ACK_ON_ERROR = 2
